name:                ShaarliHasFun
version:             0.0.1.0
github:              "mro/ShaarliHasFun"
license:             GPL-3
author:              "0x4c.de"
maintainer:          "ShaarliHasFun@0x4c.de"
copyright:           "2019 Marcus Rohrmoser"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:             Pure functional successor of the minimalist sebsauvage-shaarli, now in Haskell. 位位=
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:          Pure functional successor of the minimalist sebsauvage-shaarli, now in Haskell. 位位=

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  ShaarliHasFun.cgi:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    # https://github.com/commercialhaskell/stack/issues/3420#issuecomment-481980763
    # evtl. later https://github.com/NixOS/nixpkgs/issues/43795
    - -static
    - -O2
    cc-options: -static
    ld-options: -static -pthread
    dependencies:
    - ShaarliHasFun

tests:
  ShaarliHasFun-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ShaarliHasFun
